version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codelogdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
    - ./docker/db/data:/var/lib/mysql
    # - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codelogdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      DB_HOST: db
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db