version: '3.7'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
    - ./db/data:/var/lib/mysql
    ports:
    - 3306:3306

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: codelogdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      DB_HOST: db
    volumes:
      - ./server:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db